### PR TITLE
Implement v2 of the api

### PR DESCRIPTION
**Pull request by george-angel**

### CODE REVIEW

**Comment by tamas-molnar** [comment]
Looks good. Why was the TTL increased though?

**Comment by george-angel** [comment]
Thats the default in DYN, happy to change it back to `600`

**Comment by tamas-molnar** [comment]
I'd rather we left it alone if it worked so far.

**Comment by tamas-molnar** [comment]
+1

**Comment by kovacshuni** [comment]
+1

**Pull request merged**
